/*
 * multi_table.p4 — BMv2 v1model
 * Generated by Claude Sonnet 4.6
 */
#include <core.p4>
#include <v1model.p4>

typedef bit<32> ip4Addr_t;
typedef bit<48> macAddr_t;

header ethernet_t {
    macAddr_t dstAddr;
    macAddr_t srcAddr;
    bit<16>   etherType;
}

header ipv4_t {
    bit<4>  version;
    bit<4>  ihl;
    bit<8>  diffserv;
    bit<16> totalLen;
    bit<8>  ttl;
    bit<8>  protocol;
    bit<16> hdrChecksum;
    ip4Addr_t srcAddr;
    ip4Addr_t dstAddr;
}

struct metadata_t {
    bit<32> flow_tag;    // set by lookup table
    bit<1>  is_sensitive;
}

struct headers_t {
    ethernet_t ethernet;
    ipv4_t     ipv4;
}

// Stateful register: tracks per-flow counters
register<bit<32>>(1024) flow_counter;
register<bit<32>>(1024) audit_log;

/*************************************************************************
 *  Parser
 *************************************************************************/
parser MyParser(packet_in pkt,
                out headers_t hdr,
                inout metadata_t meta,
                inout standard_metadata_t standard_metadata) {

    state start {
        transition parse_ethernet;
    }

    state parse_ethernet {
        pkt.extract(hdr.ethernet);
        transition select(hdr.ethernet.etherType) {
            0x0800: parse_ipv4;
            default: accept;
        }
    }

    state parse_ipv4 {
        pkt.extract(hdr.ipv4);
        transition accept;
    }
}

// -----------------------------------------------
// Control: two call sites for `classify`
// -----------------------------------------------
control MyIngress(inout headers_t hdr,
                  inout metadata_t meta,
                  inout standard_metadata_t std_meta) {

    // -----------------------------------------------
    // Action: sets flow_tag from control-plane param
    // -----------------------------------------------
    action tag_flow(bit<32> tag) {
        meta.flow_tag = tag;          // param -> meta.flow_tag
    }

    action mark_sensitive() {
        meta.is_sensitive = 1;
    }

    action noop() { }

    // -----------------------------------------------
    // Shared table: called from multiple call sites
    // -----------------------------------------------
    table classify {
        key = { hdr.ipv4.srcAddr : lpm; }
        actions = { tag_flow; mark_sensitive; noop; }
        default_action = noop();
    }

    // -----------------------------------------------
    // Action: uses flow_tag to index register
    // -----------------------------------------------
    action update_counter() {
        bit<32> val;
        flow_counter.read(val, meta.flow_tag);   // flow_tag used as index
        val = val + 1;
        flow_counter.write(meta.flow_tag, val);
    }

    action write_audit() {
        bit<32> val;
        audit_log.read(val, meta.flow_tag);      // flow_tag used as index
        audit_log.write(meta.flow_tag, 42);
    }

    table update_stats {
        key = { meta.flow_tag : exact; }
        actions = { update_counter; noop; }
        default_action = noop();
    }

    table log_access {
        key = { meta.is_sensitive : exact; }
        actions = { write_audit; noop; }
        default_action = noop();
    }

    apply {
        // ip_src -> set is_sensitive -> swap -> ip_src (=dst) -> update stats
        // Call site 1: classify to set is_sensitive
        classify.apply();

        // swap
        ip4Addr_t tmpAddr = hdr.ipv4.dstAddr;
        hdr.ipv4.dstAddr = hdr.ipv4.srcAddr;
        hdr.ipv4.srcAddr = tmpAddr;

        // Call site 2: classify again to set flow_tag
        classify.apply();
        if (meta.is_sensitive == 1) {
            update_stats.apply();    // uses meta.flow_tag -> flow_counter
        }
    }
}

/*************************************************************************
 *  Egress Control (pass-through)
 *************************************************************************/
control MyEgress(inout headers_t hdr,
                 inout metadata_t meta,
                 inout standard_metadata_t standard_metadata) {
    apply { }
}

/*************************************************************************
 *  Checksum Verification / Computation (pass-through)
 *************************************************************************/
control MyVerifyChecksum(inout headers_t hdr, inout metadata_t meta) {
    apply { }
}

control MyComputeChecksum(inout headers_t hdr, inout metadata_t meta) {
    apply { }
}

/*************************************************************************
 *  Deparser
 *************************************************************************/
control MyDeparser(packet_out pkt, in headers_t hdr) {
    apply {
        pkt.emit(hdr.ethernet);
        pkt.emit(hdr.ipv4);
    }
}

/*************************************************************************
 *  Switch Instantiation
 *************************************************************************/
V1Switch(
    MyParser(),
    MyVerifyChecksum(),
    MyIngress(),
    MyEgress(),
    MyComputeChecksum(),
    MyDeparser()
) main;

